AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Parameters:
  LogLevel:
    Type: String
    Default: INFO
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicPolicy: True
        BlockPublicAcls: True

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Sid: AllowCloudFormation
          Effect: Allow
          Principal: {"Service": "cloudformation.amazonaws.com"},
          Action: s3:GetObject
          Resource: !Sub "arn:aws:s3:::${Bucket}/*"

  Function:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.8
      MemorySize: 1024
      Timeout: 900
      CodeUri: ./src
      Handler: cfn_macro_handler.handler
      Environment:
        Variables:
          BUCKET: !Ref Bucket
          LOG_LEVEL: !Ref LogLevel
      Policies:
        Version: "2012-10-17"
        Statement:
        - Sid: AllowCloudFormation
          Effect: Allow
          Action: s3:PutObject
          Resource: !Sub "arn:aws:s3:::${Bucket}/*"

  Macro:
    Type: AWS::CloudFormation::Macro
    Properties:
      Name: AWSSSOUtil
      # Description: String
      FunctionName: !Ref Function
      # LogGroupName: String
      # LogRoleARN: String
